server:
  port: 8004
spring:
  application:
    name: gateway
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin123@127.0.0.1:8000/eureka/
zuul:
  routes:
    user-ms:
      path: /user/**
      strip-prefix: true
    role-ms:
      path: /role/**
      strip-prefix: true