server:
  port: 8803
spring:
  application:
    name: user-ms
  zipkin:
    base-url: http://localhost:8808 # ZipkinServer地址
  sleuth:
    sampler:
      probability: 1.0 # 阈值，表示上报所有调用链路信息
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin123@127.0.0.1:8000/eureka/
#role-ms:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
feign:
  hystrix:
    enabled: true